### ISSUE TITLE
\name and \list are deprecated in biblatex. change to \field.

### ISSUE THREAD

**Issue by Nunkulla** [PaulStanley/oscola-biblatex#3]
Warning messages are being generated due to the use of \name and \list in the sorting scheme defined in lines 2876-2904 of the oscola.bbx file. These need to be replaced with \field.

**Comment by Nunkulla** [comment]
While the bibliography is still successfully produced, an error is generated when 'blx@firstinits' is encountered. The error points to Package etoolbox. I understand 'firstinits' may be deprecated and  'giveninits' should be used instead.

**Comment by PaulStanley** [comment]
Done and will be in release 1.5.
