### ISSUE TITLE
ELI number for EU legislation

### ISSUE THREAD

**Issue by rriemann** [PaulStanley/oscola-biblatex#7]
Hello,

I saw that documents such as http://eur-lex.europa.eu/eli/reg/2016/679/oj have an ELI url http://eur-lex.europa.eu/eli/reg/2016/679/oj.

I guess this is similar to the ECLI number for cases. Could support for this be added likewise?

**Comment by PaulStanley** [comment]
The ELI number is actually, as I understand it, a much more ambitious plan to produce a form of URL for all EU legislation. The right thing to do if you wanted to use it would be to use the ELI resource indicator as a URL, I think. I'm amending the way EU legislation is printed to make sure that will work, and I'll add a note to the manual.
